### ISSUE TITLE
EntityFocusAPI Deserialization Issue w/ lastDate Field

### ISSUE THREAD

**Issue by johnmagrini** [factset/enterprise-sdk#15]
- **com.factset.sdk.factsetrbics**:
- **0.21.3**:
- **Java 11**:
- **Linux**:

**Describe the bug**
EntityFocusAPI seems like the java DTO is out of sync with the API REST Response.  The Http response is returning 200 SUCCESS, but the JSON response is missing the DTO mandatory field lastDate. This is causing a deserializing failure:

`javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:900) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:845) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340) ~[jersey-client-2.35.jar:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104) ~[jersey-client-2.35.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365) ~[jersey-common-2.35.jar:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244) ~[jersey-client-2.35.jar:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101) ~[jersey-client-2.35.jar:na]
	at com.factset.sdk.FactSetRBICS.ApiClient.deserialize(ApiClient.java:892) ~[factsetrbics-0.21.3.jar:na]
	at com.factset.sdk.FactSetRBICS.ApiClient.invokeAPI(ApiClient.java:1093) ~[factsetrbics-0.21.3.jar:na]
	at com.factset.sdk.FactSetRBICS.api.EntityFocusApi.getRbicsEntityFocusWithHttpInfo(EntityFocusApi.java:152) ~[factsetrbics-0.21.3.jar:na]
	at com.factset.sdk.FactSetRBICS.api.EntityFocusApi.getRbicsEntityFocus(EntityFocusApi.java:87) ~[factsetrbics-0.21.3.jar:na]`

`Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'lastDate' (index 3)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 837] (through reference chain: com.factset.sdk.FactSetRBICS.models.EntityFocusResponse["data"]->java.util.ArrayList[0]->com.factset.sdk.FactSetRBICS.models.EntityFocus["lastDate"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1755) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer._findMissing(PropertyValueBuffer.java:192) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.getParameters(PropertyValueBuffer.java:158) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:518) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176) ~[jackson-databind-2.13.3.jar:2.13.3]
`

In the DTO com.factset.sdk.FactSetRBICS.models.EntityFocus  the field is mandatory 

**To Reproduce**

```
EntityFocusResponse rbicsEntityFocus = entityFocusApi.getRbicsEntityFocus(Arrays.asList(NNKD2Y-R),"2023-05-01", null, true);
```

**Expected behavior**
Result should be deserialized successfully.

**Comment by granitdula** [comment]
Hi @johnmagrini, thanks for filing this issue.

We will look into this and get back to you as soon as we can.
